ipset=/bt2.t-ru.org/bad
ipset=/bt3.t-ru.org/bad
ipset=/bt4.t-ru.org/bad
ipset=/bt.t-ru.org/bad

ipset=/2ip.io/bad
ipset=/2ip.ru/bad
ipset=/adygeya.ru/bad
ipset=/altai.ru/bad
ipset=/amur.ru/bad
ipset=/arkhangelsk.ru/bad
ipset=/astrakhan.ru/bad
ipset=/avito.ru/bad
ipset=/avito.st/bad
ipset=/avtodor-tr.ru/bad
ipset=/b2c-ticket-sentry.onelya.ru/bad
ipset=/bashkiria.ru/bad
ipset=/belgorod.ru/bad
ipset=/bir.ru/bad
ipset=/bitrix.info/bad
ipset=/biz.mail.ru/bad
ipset=/bkvet.ru/bad
ipset=/bryansk.ru/bad
ipset=/buryatia.ru/bad
ipset=/cbg.ru/bad
ipset=/cbr.ru/bad
ipset=/cdn1.ozonusercontent.com/bad
ipset=/chel.ru/bad
ipset=/chelyabinsk.ru/bad
ipset=/chita.ru/bad
ipset=/chukotka.ru/bad
ipset=/chuvashia.ru/bad
ipset=/cikrf.ru/bad
ipset=/cms1.dzvr.ru/bad
ipset=/counter.yadro.ru/bad
ipset=/crimea.ru/bad
ipset=/dagestan.ru/bad
ipset=/dzvr.ru/bad
ipset=/edu.ru/bad
ipset=/ekburg.ru/bad
ipset=/emias.info/bad
ipset=/fairplay-proxy.ott.yandex.ru/bad
ipset=/fssp.gov.ru/bad
ipset=/get-v6.2ip.io/bad
ipset=/gosuslugi.ru/bad
ipset=/gov.ru/bad
ipset=/graphql.kinopoisk.ru/bad
ipset=/grozny.ru/bad
ipset=/gu-st.ru/bad
ipset=/id.vk.com/bad
ipset=/id.vk.ru/bad
ipset=/imgsmail.ru/bad
ipset=/i-ola.ru/bad
ipset=/irk.ru/bad
ipset=/irkutsk.ru/bad
ipset=/ivanovo.ru/bad
ipset=/izhevsk.ru/bad
ipset=/jamal.ru/bad
ipset=/jar.ru/bad
ipset=/kalmykia.ru/bad
ipset=/kaluga.ru/bad
ipset=/kamchatka.ru/bad
ipset=/karelia.ru/bad
ipset=/kazan.ru/bad
ipset=/kchr.ru/bad
ipset=/kemerovo.ru/bad
ipset=/khabarovsk.ru/bad
ipset=/khakassia.ru/bad
ipset=/khv.ru/bad
ipset=/kinopoisk.ru/bad
ipset=/kirov.ru/bad
ipset=/koenig.ru/bad
ipset=/kostroma.ru/bad
ipset=/krasnodar.su/bad
ipset=/krasnoyarsk.ru/bad
ipset=/kuban.ru/bad
ipset=/kurgan.ru/bad
ipset=/kursk.ru/bad
ipset=/lemanapro.ru/bad
ipset=/leroymerlin.ru/bad
ipset=/lipetsk.ru/bad
ipset=/magadan.ru/bad
ipset=/mail.ru/bad
ipset=/mari-el.ru/bad
ipset=/marine.ru/bad
ipset=/mari.ru/bad
ipset=/mcs.mail.ru/bad
ipset=/mgfoms.ru/bad
ipset=/mobileapp.russianpost.ru/bad
ipset=/mordovia.ru/bad
ipset=/mosenergosbyt.ru/bad
ipset=/mosreg.ru/bad
ipset=/mos.ru/bad
ipset=/mts.ru/bad
ipset=/murmansk.ru/bad
ipset=/mycdn.me/bad
ipset=/nalchik.ru/bad
ipset=/nalog.ru/bad
ipset=/nn.ru/bad
ipset=/novosibirsk.ru/bad
ipset=/nov.ru/bad
ipset=/nsk.ru/bad
ipset=/ok.ru/bad
ipset=/omsk.ru/bad
ipset=/orb.ru/bad
ipset=/oryol.ru/bad
ipset=/ozone.ru/bad
ipset=/ozon.ru/bad
ipset=/ozonusercontent.com/bad
ipset=/penza.ru/bad
ipset=/perm.ru/bad
ipset=/pesc.ru/bad
ipset=/pochta.ru/bad
ipset=/pskov.ru/bad
ipset=/psk.ru/bad
ipset=/ptz.ru/bad
ipset=/pubg.mail.ru/bad
ipset=/reso.ru/bad
ipset=/rkomi.ru/bad
ipset=/rnd.ru/bad
ipset=/rosreestr.gov.ru/bad
ipset=/ryazan.ru/bad
ipset=/rzd-bonus.ru/bad
ipset=/rzd.ru/bad
ipset=/sakhalin.ru/bad
ipset=/samara.ru/bad
ipset=/saratov.ru/bad
ipset=/sberbank.ru/bad
ipset=/sevastopol.ru/bad
ipset=/sev.ru/bad
ipset=/showip.net/bad
ipset=/simbirsk.ru/bad
ipset=/smolensk.ru/bad
ipset=/spb.ru/bad
ipset=/static.2ip.io/bad
ipset=/stavropol.ru/bad
ipset=/stv.ru/bad
ipset=/surgut.ru/bad
ipset=/sys.refocus.ru/bad
ipset=/t2.ru/bad
ipset=/tambov.ru/bad
ipset=/tatarstan.ru/bad
ipset=/tom.ru/bad
ipset=/tomsk.ru/bad
ipset=/tsaritsyn.ru/bad
ipset=/tsk.ru/bad
ipset=/tula.ru/bad
ipset=/tuva.ru/bad
ipset=/tver.ru/bad
ipset=/tyumen.ru/bad
ipset=/udm.ru/bad
ipset=/udmurtia.ru/bad
ipset=/ulan-ude.ru/bad
ipset=/vk.com/bad
ipset=/vk.ru/bad
ipset=/vladikavkaz.ru/bad
ipset=/vladimir.ru/bad
ipset=/vladivostok.ru/bad
ipset=/vlg.ru/bad
ipset=/vl.ru/bad
ipset=/volgograd.ru/bad
ipset=/vologda.ru/bad
ipset=/voronezh.ru/bad
ipset=/vrn.ru/bad
ipset=/vshark.ttk.ru/bad
ipset=/vtb.ru/bad
ipset=/vyatka.ru/bad
ipset=/wf.mail.ru/bad
ipset=/widevine-proxy.ott.yandex.ru/bad
ipset=/www.2ip.io/bad
ipset=/www.2ip.ru/bad
ipset=/www.static.2ip.io/bad
ipset=/xn--80acgfbsl1azdqr.xn--p1ai/bad
ipset=/xn--90aijkdmaud0d.xn--p1ai/bad
ipset=/yadi.sk/bad
ipset=/yakutia.ru/bad
ipset=/yamal.ru/bad
ipset=/yandex.net/bad
ipset=/yaroslavl.ru/bad
ipset=/yastatic.net/bad
ipset=/yuzhno-sakhalinsk.ru/bad
